<?php

namespace wh1110000\CmsL8\Providers;

use wh1110000\CmsL8\Providers\AbstractServiceProvider;

/**
 * Class MediaServiceProvider
 * @package Workhouse\Media\Providers
 */

class MediaServiceProvider extends AbstractServiceProvider {

	public function register() {

		parent::register(); // TODO: Change the autogenerated stub

		$this->app->singleton('MediaLibrary', function ($app) {

			return \Media::get();
		});
	}
}
